url: https://jekyllconf.com/
share_message: "I'm going to @JekyllConf, the free, online conference for all things @jekyllrb"
collections:
  2015_sponsors:
  2015_speakers:
  2016_speakers:
  2019_speakers:


title: JekyllConf
description: The free, online global conference for all things Jekyll
register_link: https://eepurl.com/gvb35b
